import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import CustomFooter from './components/Footer';
import {} from 'next-intl';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex h-screen flex-col justify-between antialiased`}
      >
        <Navbar />

        <main className='mb-auto h-10 justify-center lg:pl-[19.5rem]'>
          {children}
        </main>

        <CustomFooter />
      </body>
    </html>
  );
}
